all:
	g++  -Wall -Werror -g -I/home/ben/github/ustandard//test -I/home/ben/github/ustandard/include -L/home/ben/github/ustandard/lib -lustandard -Wl,-rpath=/home/ben/github/ustandard/lib -lpthread -lrt t.cpp
